name: turquoise
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  firebase_core: ^2.23.0  # add dependency for Firebase Core
  cloud_firestore: ^4.13.2  # add dependency for Cloud Firestore
  cached_network_image: ^3.2.1
  flutter_svg: ^2.0.9
  intl: ^0.18.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterLight.ttf
          weight: 300
